//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDocuments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.PointDocConnections = new HashSet<PointDocConnection>();
        }
    
        public int id { get; set; }
        public int DocType { get; set; }
        public string Name { get; set; }
    
        public virtual DocumentHistory DocumentHistory { get; set; }
        public virtual Document Documents1 { get; set; }
        public virtual Document Document1 { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointDocConnection> PointDocConnections { get; set; }
    }
}
