//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDocuments
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentHistory
    {
        public int id { get; set; }
        public int DocumentID { get; set; }
        public byte[] DocumentBinary { get; set; }
        public System.DateTime Date { get; set; }
        public string UserName { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
