//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDocuments
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointDocConnection
    {
        public int id { get; set; }
        public int PointID { get; set; }
        public int DocumentID { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Point Point { get; set; }
    }
}
